import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProgressBar from "@/components/ui/ProgressBar";
import ImageSlide from "@/components/ui/ImageSlide";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Logical",
  description: "Generated by Logical",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={` relative`}>
          <ProgressBar />
          <ImageSlide />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
